### ISSUE TITLE
Perform a Pull on Each Repository

### ISSUE THREAD

**Issue by Linuturk** [stevenjack/cig#12]
It would be nice to pull down any upstream changes on master for `origin` and/or `upstream`.

**Comment by JakeChampion** [comment]
I'm not sure this fits with the goal of CIG ("Can I go?"). Executing a pull makes me think more of "Let's Start Work".

If it were to be added as a feature, some questions need to be answered:
- How would you handle conflicts for each individual repo?
- How do we know which Git remote to pull from?
