### ISSUE TITLE
Detached HEAD will show a change (P), even if there is nothing different

### ISSUE THREAD

**Issue by Ari-E-S** [stevenjack/cig#40]
Hi!

I'm currently using cig in my development and it behaves quite nicely except with detached HEADs.
Terraform can get dependencies via a checkout and in some instances, it may result in a detached HEAD.

I think this could be detected in this line: https://github.com/stevenjack/cig/blob/master/repo/repo.go#L56
I don't think my skills in GO are enough to fix it, though.

Regards!
    --Ariel

**Comment by stevenjack** [comment]
hey @arielsalvo, glad the tool is useful for you! I'll take a look over the weekend and see if I can get a PR up for it.
